name: Build and Deploy

on:
  push:
    branches:
      - main  # Set your default branch here
  # You can also trigger on other events like pull_request, or manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: |
        # Your build commands go here
        # For example, if you're using a Makefile:
        make all

    - name: Deploy to production
      env:
        DEPLOY_SERVER: root@example.com
        DEPLOY_PATH: /root/prod/foobar
        # You can store the SSH_PRIVATE_KEY in the repository secrets
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        # Install ssh-agent if not already present
        if [ ! -d ~/.ssh ]; then
          mkdir ~/.ssh
        fi
        # Start the ssh agent
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${SSH_PRIVATE_KEY}"
        # Add the server to known_hosts
        ssh-keyscan -H "${DEPLOY_SERVER#*@}" >> ~/.ssh/known_hosts
        # Rsync files
        rsync -avz --delete ./build/ "${DEPLOY_SERVER}:${DEPLOY_PATH}"
      shell: bash


