name: Build and Deploy

on:
  push:
    branches:
      - main  # Set your default branch here
  # You can also trigger on other events like pull_request, or manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: |
        # cargo build --release
        echo "rsync works!" >> foo 

    - name: Deploy
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        # path: ./target/release/api
        path: foo
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        
