name: Build and Deploy

on:
  push:
    branches:
      - main  # Set your default branch here
  # You can also trigger on other events like pull_request, or manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: |
        # cargo build --release
        echo "rsync works!" >> foo

    - name: Install rsync and ssh
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync openssh-client

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

    - name: Rsync binary to remote server
      run: |
        # Replace the following placeholders with actual values
        rsync -avz --progress -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" ./foo ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
